/* Automatically generated by tree-sitter v0.25.1 (f5afe475deb7c0bae6407fb776c76824f717bb61) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 34
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 35
#define ALIAS_COUNT 0
#define TOKEN_COUNT 17
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  aux_sym__headers_token1 = 1,
  sym_header_separator = 2,
  sym_header_field = 3,
  anon_sym_From = 4,
  anon_sym_To = 5,
  anon_sym_Cc = 6,
  anon_sym_Bcc = 7,
  anon_sym_Reply_DASHTo = 8,
  sym_header_field_subject = 9,
  sym_header_unstructured = 10,
  sym_atom = 11,
  sym_quoted_string = 12,
  sym_email = 13,
  sym_quote_marker = 14,
  sym_quote_contents = 15,
  aux_sym__body_line_token1 = 16,
  sym_source_file = 17,
  aux_sym__headers = 18,
  sym__header = 19,
  sym_header_email = 20,
  sym_header_other = 21,
  sym_header_subject = 22,
  sym_header_field_email = 23,
  sym_body_separator = 24,
  sym_body = 25,
  sym_quote_block = 26,
  sym__quoted_line = 27,
  sym_body_block = 28,
  sym__body_line = 29,
  sym__empty_line = 30,
  aux_sym_header_email_repeat1 = 31,
  aux_sym_body_repeat1 = 32,
  aux_sym_quote_block_repeat1 = 33,
  aux_sym_body_block_repeat1 = 34,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [aux_sym__headers_token1] = "_headers_token1",
  [sym_header_separator] = "header_separator",
  [sym_header_field] = "header_field",
  [anon_sym_From] = "From",
  [anon_sym_To] = "To",
  [anon_sym_Cc] = "Cc",
  [anon_sym_Bcc] = "Bcc",
  [anon_sym_Reply_DASHTo] = "Reply-To",
  [sym_header_field_subject] = "header_field_subject",
  [sym_header_unstructured] = "header_unstructured",
  [sym_atom] = "atom",
  [sym_quoted_string] = "quoted_string",
  [sym_email] = "email",
  [sym_quote_marker] = "quote_marker",
  [sym_quote_contents] = "quote_contents",
  [aux_sym__body_line_token1] = "_body_line_token1",
  [sym_source_file] = "source_file",
  [aux_sym__headers] = "_headers",
  [sym__header] = "_header",
  [sym_header_email] = "header_email",
  [sym_header_other] = "header_other",
  [sym_header_subject] = "header_subject",
  [sym_header_field_email] = "header_field_email",
  [sym_body_separator] = "body_separator",
  [sym_body] = "body",
  [sym_quote_block] = "quote_block",
  [sym__quoted_line] = "_quoted_line",
  [sym_body_block] = "body_block",
  [sym__body_line] = "_body_line",
  [sym__empty_line] = "_empty_line",
  [aux_sym_header_email_repeat1] = "header_email_repeat1",
  [aux_sym_body_repeat1] = "body_repeat1",
  [aux_sym_quote_block_repeat1] = "quote_block_repeat1",
  [aux_sym_body_block_repeat1] = "body_block_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [aux_sym__headers_token1] = aux_sym__headers_token1,
  [sym_header_separator] = sym_header_separator,
  [sym_header_field] = sym_header_field,
  [anon_sym_From] = anon_sym_From,
  [anon_sym_To] = anon_sym_To,
  [anon_sym_Cc] = anon_sym_Cc,
  [anon_sym_Bcc] = anon_sym_Bcc,
  [anon_sym_Reply_DASHTo] = anon_sym_Reply_DASHTo,
  [sym_header_field_subject] = sym_header_field_subject,
  [sym_header_unstructured] = sym_header_unstructured,
  [sym_atom] = sym_atom,
  [sym_quoted_string] = sym_quoted_string,
  [sym_email] = sym_email,
  [sym_quote_marker] = sym_quote_marker,
  [sym_quote_contents] = sym_quote_contents,
  [aux_sym__body_line_token1] = aux_sym__body_line_token1,
  [sym_source_file] = sym_source_file,
  [aux_sym__headers] = aux_sym__headers,
  [sym__header] = sym__header,
  [sym_header_email] = sym_header_email,
  [sym_header_other] = sym_header_other,
  [sym_header_subject] = sym_header_subject,
  [sym_header_field_email] = sym_header_field_email,
  [sym_body_separator] = sym_body_separator,
  [sym_body] = sym_body,
  [sym_quote_block] = sym_quote_block,
  [sym__quoted_line] = sym__quoted_line,
  [sym_body_block] = sym_body_block,
  [sym__body_line] = sym__body_line,
  [sym__empty_line] = sym__empty_line,
  [aux_sym_header_email_repeat1] = aux_sym_header_email_repeat1,
  [aux_sym_body_repeat1] = aux_sym_body_repeat1,
  [aux_sym_quote_block_repeat1] = aux_sym_quote_block_repeat1,
  [aux_sym_body_block_repeat1] = aux_sym_body_block_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [aux_sym__headers_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_header_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_From] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_To] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Cc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Bcc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_Reply_DASHTo] = {
    .visible = true,
    .named = false,
  },
  [sym_header_field_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_header_unstructured] = {
    .visible = true,
    .named = true,
  },
  [sym_atom] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_string] = {
    .visible = true,
    .named = true,
  },
  [sym_email] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_contents] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__body_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__headers] = {
    .visible = false,
    .named = false,
  },
  [sym__header] = {
    .visible = false,
    .named = true,
  },
  [sym_header_email] = {
    .visible = true,
    .named = true,
  },
  [sym_header_other] = {
    .visible = true,
    .named = true,
  },
  [sym_header_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_header_field_email] = {
    .visible = true,
    .named = true,
  },
  [sym_body_separator] = {
    .visible = true,
    .named = true,
  },
  [sym_body] = {
    .visible = true,
    .named = true,
  },
  [sym_quote_block] = {
    .visible = true,
    .named = true,
  },
  [sym__quoted_line] = {
    .visible = false,
    .named = true,
  },
  [sym_body_block] = {
    .visible = true,
    .named = true,
  },
  [sym__body_line] = {
    .visible = false,
    .named = true,
  },
  [sym__empty_line] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_header_email_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quote_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_body_block_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
};

const TSCharacterRange sym_atom_character_set_1[] = {
  {'!', '!'}, {'#', '\''}, {'*', '+'}, {'-', '-'}, {'/', '9'}, {'=', '='}, {'?', '?'}, {'A', 'Z'},
  {'^', '~'}, {0x80, 0x10ffff},
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(0);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == ':') ADVANCE(11);
      if (lookahead == '<') ADVANCE(6);
      if (lookahead == '>') ADVANCE(70);
      if (lookahead == 'B') ADVANCE(53);
      if (lookahead == 'C') ADVANCE(50);
      if (lookahead == 'F') ADVANCE(63);
      if (lookahead == 'R') ADVANCE(54);
      if (lookahead == 'S') ADVANCE(65);
      if (lookahead == 'T') ADVANCE(59);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(10);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(2);
      if (lookahead == '"') ADVANCE(5);
      if (lookahead == '<') ADVANCE(6);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '>') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != '<') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '"' &&
          lookahead != '\\') ADVANCE(3);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '<' &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') SKIP(7);
      if (lookahead == 'B') ADVANCE(18);
      if (lookahead == 'C') ADVANCE(15);
      if (lookahead == 'F') ADVANCE(28);
      if (lookahead == 'R') ADVANCE(19);
      if (lookahead == 'S') ADVANCE(30);
      if (lookahead == 'T') ADVANCE(24);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(75);
      if (lookahead == '>') ADVANCE(70);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym__headers_token1);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_header_separator);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == '-') ADVANCE(13);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'T') ADVANCE(26);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'b') ADVANCE(21);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(38);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(40);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(29);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'c') ADVANCE(16);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'e') ADVANCE(17);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'j') ADVANCE(20);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'l') ADVANCE(31);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'm') ADVANCE(34);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(36);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(23);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'o') ADVANCE(42);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'p') ADVANCE(22);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'r') ADVANCE(25);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 't') ADVANCE(44);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'u') ADVANCE(14);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead == 'y') ADVANCE(12);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_header_field);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_From);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_From);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_To);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_To);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_Cc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_Bcc);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_Reply_DASHTo);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_header_field_subject);
      if (lookahead > ' ' &&
          lookahead != ':' &&
          lookahead != 0x7f) ADVANCE(32);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_header_unstructured);
      if (lookahead == ' ') ADVANCE(45);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_header_unstructured);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == '-') ADVANCE(48);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'T') ADVANCE(61);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'b') ADVANCE(56);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'c') ADVANCE(37);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'c') ADVANCE(39);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'c') ADVANCE(64);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'c') ADVANCE(51);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'e') ADVANCE(62);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'e') ADVANCE(52);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'j') ADVANCE(55);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'l') ADVANCE(66);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'm') ADVANCE(33);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'o') ADVANCE(35);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'o') ADVANCE(58);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'o') ADVANCE(41);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'p') ADVANCE(57);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'r') ADVANCE(60);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 't') ADVANCE(43);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'u') ADVANCE(49);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_atom);
      if (lookahead == 'y') ADVANCE(47);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_atom);
      if (set_contains(sym_atom_character_set_1, 10, lookahead)) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_quoted_string);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_email);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_quote_marker);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_quote_marker);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_quote_contents);
      if (lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_quote_contents);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\n') ADVANCE(10);
      if (lookahead != 0) ADVANCE(76);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead == '\r') ADVANCE(74);
      if (lookahead == ' ') ADVANCE(75);
      if (lookahead == '>') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(aux_sym__body_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(76);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 7},
  [2] = {.lex_state = 7},
  [3] = {.lex_state = 7},
  [4] = {.lex_state = 8},
  [5] = {.lex_state = 8},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 45},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 45},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 72},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [aux_sym__headers_token1] = ACTIONS(1),
    [sym_header_separator] = ACTIONS(1),
    [anon_sym_From] = ACTIONS(1),
    [anon_sym_To] = ACTIONS(1),
    [anon_sym_Cc] = ACTIONS(1),
    [anon_sym_Bcc] = ACTIONS(1),
    [anon_sym_Reply_DASHTo] = ACTIONS(1),
    [sym_header_field_subject] = ACTIONS(1),
    [sym_atom] = ACTIONS(1),
    [sym_quoted_string] = ACTIONS(1),
    [sym_email] = ACTIONS(1),
    [sym_quote_marker] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(18),
    [aux_sym__headers] = STATE(2),
    [sym__header] = STATE(23),
    [sym_header_email] = STATE(23),
    [sym_header_other] = STATE(23),
    [sym_header_subject] = STATE(23),
    [sym_header_field_email] = STATE(20),
    [sym_header_field] = ACTIONS(3),
    [anon_sym_From] = ACTIONS(5),
    [anon_sym_To] = ACTIONS(5),
    [anon_sym_Cc] = ACTIONS(5),
    [anon_sym_Bcc] = ACTIONS(5),
    [anon_sym_Reply_DASHTo] = ACTIONS(5),
    [sym_header_field_subject] = ACTIONS(7),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(3), 1,
      sym_header_field,
    ACTIONS(7), 1,
      sym_header_field_subject,
    ACTIONS(9), 1,
      ts_builtin_sym_end,
    ACTIONS(11), 1,
      aux_sym__headers_token1,
    STATE(3), 1,
      aux_sym__headers,
    STATE(5), 1,
      sym_body_separator,
    STATE(20), 1,
      sym_header_field_email,
    STATE(23), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(5), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [35] = 7,
    ACTIONS(15), 1,
      sym_header_field,
    ACTIONS(21), 1,
      sym_header_field_subject,
    STATE(3), 1,
      aux_sym__headers,
    STATE(20), 1,
      sym_header_field_email,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    STATE(23), 4,
      sym__header,
      sym_header_email,
      sym_header_other,
      sym_header_subject,
    ACTIONS(18), 5,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
  [65] = 7,
    ACTIONS(24), 1,
      ts_builtin_sym_end,
    ACTIONS(26), 1,
      aux_sym__headers_token1,
    ACTIONS(29), 1,
      sym_quote_marker,
    ACTIONS(32), 1,
      aux_sym__body_line_token1,
    STATE(8), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_block_repeat1,
    STATE(4), 4,
      sym_quote_block,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [92] = 7,
    ACTIONS(35), 1,
      aux_sym__headers_token1,
    ACTIONS(37), 1,
      sym_quote_marker,
    ACTIONS(39), 1,
      aux_sym__body_line_token1,
    STATE(31), 1,
      sym_body,
    STATE(8), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_block_repeat1,
    STATE(6), 4,
      sym_quote_block,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [119] = 7,
    ACTIONS(37), 1,
      sym_quote_marker,
    ACTIONS(39), 1,
      aux_sym__body_line_token1,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      aux_sym__headers_token1,
    STATE(8), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    STATE(10), 2,
      sym__quoted_line,
      aux_sym_quote_block_repeat1,
    STATE(4), 4,
      sym_quote_block,
      sym_body_block,
      sym__empty_line,
      aux_sym_body_repeat1,
  [146] = 2,
    ACTIONS(13), 2,
      ts_builtin_sym_end,
      aux_sym__headers_token1,
    ACTIONS(45), 7,
      sym_header_field,
      anon_sym_From,
      anon_sym_To,
      anon_sym_Cc,
      anon_sym_Bcc,
      anon_sym_Reply_DASHTo,
      sym_header_field_subject,
  [160] = 3,
    ACTIONS(47), 1,
      ts_builtin_sym_end,
    STATE(11), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
    ACTIONS(49), 3,
      aux_sym__headers_token1,
      sym_quote_marker,
      aux_sym__body_line_token1,
  [173] = 4,
    ACTIONS(51), 1,
      ts_builtin_sym_end,
    ACTIONS(55), 1,
      sym_quote_marker,
    ACTIONS(53), 2,
      aux_sym__headers_token1,
      aux_sym__body_line_token1,
    STATE(9), 2,
      sym__quoted_line,
      aux_sym_quote_block_repeat1,
  [188] = 3,
    ACTIONS(58), 1,
      ts_builtin_sym_end,
    STATE(9), 2,
      sym__quoted_line,
      aux_sym_quote_block_repeat1,
    ACTIONS(60), 3,
      aux_sym__headers_token1,
      sym_quote_marker,
      aux_sym__body_line_token1,
  [201] = 4,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 1,
      aux_sym__body_line_token1,
    ACTIONS(64), 2,
      aux_sym__headers_token1,
      sym_quote_marker,
    STATE(11), 2,
      sym__body_line,
      aux_sym_body_block_repeat1,
  [216] = 4,
    ACTIONS(69), 1,
      aux_sym__headers_token1,
    ACTIONS(73), 1,
      sym_email,
    STATE(13), 1,
      aux_sym_header_email_repeat1,
    ACTIONS(71), 2,
      sym_atom,
      sym_quoted_string,
  [230] = 4,
    ACTIONS(75), 1,
      aux_sym__headers_token1,
    ACTIONS(79), 1,
      sym_email,
    STATE(14), 1,
      aux_sym_header_email_repeat1,
    ACTIONS(77), 2,
      sym_atom,
      sym_quoted_string,
  [244] = 3,
    STATE(14), 1,
      aux_sym_header_email_repeat1,
    ACTIONS(81), 2,
      aux_sym__headers_token1,
      sym_email,
    ACTIONS(83), 2,
      sym_atom,
      sym_quoted_string,
  [256] = 2,
    ACTIONS(86), 1,
      ts_builtin_sym_end,
    ACTIONS(88), 3,
      aux_sym__headers_token1,
      sym_quote_marker,
      aux_sym__body_line_token1,
  [265] = 2,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 3,
      aux_sym__headers_token1,
      sym_quote_marker,
      aux_sym__body_line_token1,
  [274] = 1,
    ACTIONS(94), 3,
      aux_sym__headers_token1,
      sym_quote_marker,
      aux_sym__body_line_token1,
  [280] = 1,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
  [284] = 1,
    ACTIONS(98), 1,
      sym_header_unstructured,
  [288] = 1,
    ACTIONS(100), 1,
      sym_header_separator,
  [292] = 1,
    ACTIONS(102), 1,
      sym_header_unstructured,
  [296] = 1,
    ACTIONS(104), 1,
      sym_header_separator,
  [300] = 1,
    ACTIONS(106), 1,
      aux_sym__headers_token1,
  [304] = 1,
    ACTIONS(108), 1,
      sym_header_separator,
  [308] = 1,
    ACTIONS(110), 1,
      aux_sym__headers_token1,
  [312] = 1,
    ACTIONS(112), 1,
      aux_sym__headers_token1,
  [316] = 1,
    ACTIONS(114), 1,
      sym_quote_contents,
  [320] = 1,
    ACTIONS(116), 1,
      aux_sym__headers_token1,
  [324] = 1,
    ACTIONS(118), 1,
      aux_sym__headers_token1,
  [328] = 1,
    ACTIONS(120), 1,
      sym_header_separator,
  [332] = 1,
    ACTIONS(122), 1,
      ts_builtin_sym_end,
  [336] = 1,
    ACTIONS(75), 1,
      aux_sym__headers_token1,
  [340] = 1,
    ACTIONS(124), 1,
      aux_sym__headers_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 65,
  [SMALL_STATE(5)] = 92,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 146,
  [SMALL_STATE(8)] = 160,
  [SMALL_STATE(9)] = 173,
  [SMALL_STATE(10)] = 188,
  [SMALL_STATE(11)] = 201,
  [SMALL_STATE(12)] = 216,
  [SMALL_STATE(13)] = 230,
  [SMALL_STATE(14)] = 244,
  [SMALL_STATE(15)] = 256,
  [SMALL_STATE(16)] = 265,
  [SMALL_STATE(17)] = 274,
  [SMALL_STATE(18)] = 280,
  [SMALL_STATE(19)] = 284,
  [SMALL_STATE(20)] = 288,
  [SMALL_STATE(21)] = 292,
  [SMALL_STATE(22)] = 296,
  [SMALL_STATE(23)] = 300,
  [SMALL_STATE(24)] = 304,
  [SMALL_STATE(25)] = 308,
  [SMALL_STATE(26)] = 312,
  [SMALL_STATE(27)] = 316,
  [SMALL_STATE(28)] = 320,
  [SMALL_STATE(29)] = 324,
  [SMALL_STATE(30)] = 328,
  [SMALL_STATE(31)] = 332,
  [SMALL_STATE(32)] = 336,
  [SMALL_STATE(33)] = 340,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(30),
  [9] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [15] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(24),
  [18] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(22),
  [21] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0), SHIFT_REPEAT(30),
  [24] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [29] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [32] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body, 1, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__headers, 2, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_body_block, 1, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_block, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_quote_block_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quote_block_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quote_block_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [58] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quote_block, 1, 0, 0),
  [60] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quote_block, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_body_block_repeat1, 2, 0, 0), SHIFT_REPEAT(28),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [73] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [75] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_header_email_repeat1, 2, 0, 0),
  [83] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_header_email_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [86] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__body_line, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__body_line, 2, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__quoted_line, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__quoted_line, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_body_separator, 1, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_field_email, 1, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_other, 3, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_subject, 3, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_header_email, 4, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_mail(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
